name: default

kind: pipeline
type: docker


steps:
- name: mattermost
  image: dabankio/drone-plugin-mattermost
  environment:
    token:
        from_secret: mattermost_token
    host:
        from_secret: mattermost_host
    channel:
        from_secret: mattermost_channel
  settings:
    maxRetry: 3
