name: default

kind: pipeline
type: docker


steps:
# - name: docker
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: docker_name
#     password:
#       from_secret: docker_password
#     repo: hellosanta/php4drupal
#     tag: latest
- name: mattermost
  image: dabankio/drone-plugin-mattermost
  environment:
    token:
        from_secret: mattermost_token
    host:
        from_secret: mattermost_host
    channel:
        from_secret: mattermost_channel
  settings:
    maxRetry: 3
