name: default

kind: pipeline
type: docker


steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_name
    password:
      from_secret: docker_password
    repo: hellosanta/php4drupal
    tag: latest

- name: push commit
  image: appleboy/drone-git-push:0.2.0-linux-amd64
  settings:
    branch: master
    remote: git@github.com:HelloSanta/php4drupal.git
    force: false
    commit: true
    ssh_key:
      from_secret: ssh_key
