name: default

kind: pipeline
type: docker


steps:
- name: push commit
  image: appleboy/drone-git-push:0.2.0-linux-amd64
  settings:
    branch: create-notify
    remote: git@github.com:HelloSanta/php4drupal.git
    force: false
    commit: true
    ssh_key:
      from_secret: ssh_key

- name: send
  image: plugins/webhook
  settings:
    urls:
      from_secret: mattermost_webhook
    content_type: application/json
    template: |
      {
        "owner": "{{ repo.owner }}",
        "repo": "{{ repo.name }}",
        "status": "{{ build.status }}",
        "channel": "s3o98479njgnjdb34tw47tad1a"
        "text": "sample"
      }
  when:
    status:
    - failure
    - success
