name: default

kind: pipeline
type: docker


steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_name
    password:
      from_secret: docker_password
    repo: hellosanta/php4drupal
    tag: php7.3-apache


